name: Build

on:
  push:
    branches: [ main, beta ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        filter: blob:none
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk

    - name: Set release tag
      id: set-tag
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
          echo "title=Latest" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref_name }}" = "beta" ]; then
          echo "tag=beta" >> $GITHUB_OUTPUT
          echo "title=Beta" >> $GITHUB_OUTPUT
        fi

    - name: Generate release notes
      run: git log refs/tags/${{ steps.set-tag.outputs.tag }}..HEAD --oneline --decorate=no > notes.txt 2>/dev/null || git log -10 --oneline --decorate=no > notes.txt

    - name: Update tag
      run: |
        git tag -f ${{ steps.set-tag.outputs.tag }}
        git push -f origin tag ${{ steps.set-tag.outputs.tag }}

    - name: Delete release
      continue-on-error: true
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete ${{ steps.set-tag.outputs.tag }} -y

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release create ${{ steps.set-tag.outputs.tag }} --title "${{ steps.set-tag.outputs.title }}" --notes-file notes.txt --latest=true 'app/build/outputs/apk/release/*.apk'
